[project]
name = "transpop-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "matplotlib>=3.10.6",
    "numpy>=2.3.2",
    "openai>=1.98.0",
    "pandas>=2.3.2",
]
